### ISSUE TITLE
Quarkus 3.5.x breaks quarkus-operator-sdk

### ISSUE THREAD

**Issue by Jeansen** [quarkiverse/quarkus-operator-sdk#753]
My sandbox project builds just fine until Quarkus 3.4.3. When I bump Quarkus to 3.5.x, it no longer works.

Project: https://github.com/Jeansen/cert-operator

```
2023-11-10 10:11:58,782 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.IncompatibleClassChangeError: Found class io.fabric8.kubernetes.api.model.rbac.ClusterRoleFluent$MetadataNested, but interface was expected
	at io.quarkiverse.operatorsdk.deployment.AddClusterRolesDecorator.createClusterRole(AddClusterRolesDecorator.java:76)
	at io.quarkiverse.operatorsdk.deployment.AddClusterRolesDecorator.lambda$visit$0(AddClusterRolesDecorator.java:36)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at io.quarkiverse.operatorsdk.deployment.AddClusterRolesDecorator.visit(AddClusterRolesDecorator.java:35)
	at io.quarkiverse.operatorsdk.deployment.AddClusterRolesDecorator.visit(AddClusterRolesDecorator.java:19)
	at io.fabric8.kubernetes.api.builder.Visitor.visit(Visitor.java:26)
	at io.fabric8.kubernetes.api.builder.VisitorWiretap.visit(VisitorWiretap.java:44)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:88)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:75)
	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:54)
	at io.dekorate.ResourceRegistry.lambda$generate$2(ResourceRegistry.java:181)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at io.dekorate.ResourceRegistry.generate(ResourceRegistry.java:173)
	at io.dekorate.Session.generate(Session.java:293)
	at io.dekorate.Session.close(Session.java:256)
	at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$2(KubernetesProcessor.java:194)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:142)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```

**Comment by metacosm** [comment]
Hi, the Fabric8 client was updated in Quarkus 3.5.0 and QOSDK has not yet been released to work with 3.5.x. We are actually waiting on https://github.com/quarkusio/quarkus/pull/36312 because 6.8.1 and later caused some type inference issues, which hopefully should be addressed with 6.9.2.

**Comment by Jeansen** [comment]
Oh, I see. Anyway, I tried 6.4.0.Beta1 and it looks fine so far. That is, I no longer have any exceptions and my mini project works as expected again :+1:

**Comment by Jeansen** [comment]
Should I close this one or should we leave it open for reference until everything is released on the stable track?

**Comment by metacosm** [comment]
Let's keep this open until we have a final release for 3.5. Thank you!

**Comment by metacosm** [comment]
6.4.0 has been released, closing this now.

**Comment by sorend** [comment]
@metacosm Sorry for mentioning on this old ticket. I have just tried 6.4.0 and it seems there is some problem with versioning.

I do not have an in-depth analysis of the problem yet, so just mentioning it tentatively here. I believe the problem stems from:
```
<properties>
<quarkus.version>3.5.2</quarkus.version>
<java-operator-sdk.version>4.5.0</java-operator-sdk.version>
</properties>
```

Quarkus 3.5.2 brings in  io.fabric8:kubernetes-client:6.8.1 while java-operator-sdk 4.5.0 wants io.fabric8:kubernetes-client:6.7.2, and I end up with something like `Caused by: java.lang.NoClassDefFoundError: io.fabric8.kubernetes.client.CustomResourceFluentImpl`.
