### ISSUE TITLE
Build with QOSDK 6.6.0 fails -> NoSuchMethodError: io.quarkus.arc.runtime.ArcRecorder.initContainer

### ISSUE THREAD

**Issue by Jeansen** [quarkiverse/quarkus-operator-sdk#813]
I've tried to bump my sandbox project after some weeks to current versions of Quarkus and QOSDK. Current versions of Quarkus work fine with version 6.5.1, from Quarkus 3.5.x to 3.6.x. The latest version combination that I can successfully build is with QOSDK 6.5.1 and Quarkus 3.6.8. 

I pushed the latest compiling version to https://github.com/Jeansen/cert-operator.

But using QOSDK version 6.6.0 release a couple days ago results in the following stack trace:

```
Execution failed for task ':quarkusAppPartsBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#initializeContainer threw an exception: java.lang.NoSuchMethodError: 'io.quarkus.arc.ArcContainer io.quarkus.arc.runtime.ArcRecorder.initContainer(io.quarkus.runtime.ShutdownContext, io.quarkus.runtime.RuntimeValue, boolean)'
        	at io.quarkus.arc.deployment.ArcProcessor.initializeContainer(ArcProcessor.java:615)
        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
        	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
        	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        	at java.base/java.lang.Thread.run(Thread.java:833)
        	at org.jboss.threads.JBossThread.run(JBossThread.java:501)


```

**Comment by metacosm** [comment]
@Jeansen Could you please confirm that the proposed resolution works for you? Making the changes above addressed the issue for me when I tried on your project.

**Comment by metacosm** [comment]
Closing this as I think this is resolved. Please re-open if you're still seeing an issue.

**Comment by Jeansen** [comment]
@metacosm Yes, that worked for me, too. Compiles and runs against my local cluster! Thanks for the insight. Closing.
