### PR TITLE
fix: make things compile with Quarkus 2.8

### LINKED ISSUE #310: Operator SDK with Quarkus 2.8.0
Are there any plans to have any time soon a new version that is compatible with quarkus 2.8.0.Final?

Currently upgrading with latest `3.0.7` and there is library (decorate) mismatch that fails at build time with following error:

````
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.8.0.Final:build (default) on project mysql-operator: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.NoSuchMethodError: 'io.fabric8.kubernetes.api.model.ObjectMeta io.quarkiverse.operatorsdk.deployment.AddRoleBindingsDecorator.getMandatoryDeploymentMetadata(io.fabric8.kubernetes.api.model.KubernetesListBuilder)'
[ERROR] 	at io.quarkiverse.operatorsdk.deployment.AddRoleBindingsDecorator.visit(AddRoleBindingsDecorator.java:37)
[ERROR] 	at io.quarkiverse.operatorsdk.deployment.AddRoleBindingsDecorator.visit(AddRoleBindingsDecorator.java:19)
[ERROR] 	at io.fabric8.kubernetes.api.builder.BaseFluent.acceptInternal(BaseFluent.java:96)
[ERROR] 	at io.fabric8.kubernetes.api.builder.BaseFluent.accept(BaseFluent.java:75)
[ERROR] 	at io.dekorate.ResourceRegistry.lambda$generate$3(ResourceRegistry.java:179)
[ERROR] 	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
[ERROR] 	at io.dekorate.ResourceRegistry.generate(ResourceRegistry.java:173)
[ERROR] 	at io.dekorate.Session.generate(Session.java:285)
[ERROR] 	at io.dekorate.Session.close(Session.java:248)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$2(KubernetesProcessor.java:173)
[ERROR] 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
[ERROR] 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:126)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
````

Looks like decorate 2.8.1 that is used by 3.0.7 has changed in 2.9.0 that is used by quarkus 2.8.0 - method signature has been changed - added new parameter.

### PR DESCRIPTION
**Pull request by metacosm**
Fixes #310, though, hopefully, Quarkus 2.8.1 will allow us to avoid this fix.

### CODE REVIEW

**Comment by mswiderski** [comment]
any plans to get this merged? Quarkus 2.8.1 is already released.

**Comment by metacosm** [comment]
> any plans to get this merged? Quarkus 2.8.1 is already released.

Actually, using Quarkus 2.8.1 doesn't require this fix anymore.

**Comment by mswiderski** [comment]
@metacosm you're totally right, upgrading to 2.8.1 makes it work with 3.0.7, thanks a lot
